### ISSUE TITLE
Why you use channel-wise concatenation when fusion feature maps from multi-scales in 'class down' step, that's different from the Fig3 in paper. Is there any improvements when using concatenation rather than summation? 

### ISSUE THREAD

**Issue by lufanma** [DIAL-RPI/PIPO-FAN#3]

**Comment by seconds7** [comment]
Hi, @Lufan111 ,

Thanks for your question,. Here we use concatenation rather than summation in PIPO. We didn't compare the performance of "summation" and "concatenation in 'class down' step. However, We've tried "summation" for all features across different scales after same number of convolutions. It brings clear improvement in training and validation proced

**Comment by xifang001** [comment]
Hi, @Lufan111 ,

Thanks for your question. Both summation and concatenation are helpful. Two fusion way may be considered to decide the fusion mechanism. When applied in LiTS data, concatenation brings better improvement. There are also other ways to enhance the multi-scale feature, we've tried "summation" for all features across different scales after same number of convolutions. It also brings clear improvement on the framework. It can be found at "Fang, Xi, et al. "Unified multi-scale feature abstraction for medical image segmentation." Medical Imaging 2020: Image Processing. " Hope that can be helpful.

Best,
Xi
